### ISSUE TITLE
socket.error: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by famousoldys** [Juniorn1003/Faitagram#12]
1. i tested with wordlist (wlist)

Username: sxxxxxxxxxxxxxx -> Password found: 123456

Traceback (most recent call last):
  File "faitagram", line 342, in <module>
    main()
  File "faitagram", line 102, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 168, in execute
    self.webBruteforce(self.username, self.wordlist, self.service, self.delay)
  File "faitagram", line 326, in webBruteforce
    self.stopTOR()
  File "faitagram", line 124, in stopTOR
    driver.close()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 510, in close
    self.execute(Command.CLOSE)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 432, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

2. i tested with my own worldist

Error : 'utf8' codec can't decode byte 0xc2 in position 0: unexpected end of data
Traceback (most recent call last):
  File "faitagram", line 342, in <module>
    main()
  File "faitagram", line 102, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 168, in execute
    self.webBruteforce(self.username, self.wordlist, self.service, self.delay)
  File "faitagram", line 334, in webBruteforce
    self.stopTOR()
  File "faitagram", line 124, in stopTOR
    driver.close()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 510, in close
    self.execute(Command.CLOSE)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 234, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 401, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 432, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
socket.error: [Errno 111] Connection refused

**Comment by Juniorn1003** [comment]
What is the version of the gecko driver?

**Comment by Juniorn1003** [comment]
Wait, Socket? That was the previous version! Clone the script again.
