### ISSUE TITLE
tor_process not defined

### ISSUE THREAD

**Issue by PlaguedByWeirdness** [Juniorn1003/Faitagram#15]
Hey,
There were some IndentationError's and I fixed them by adjusting spaces and stuff, but after that I get the:
sh: 1: m: not found
Traceback (most recent call last):
  File "faitagram", line 279, in <module>
    main()
  File "faitagram", line 58, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 120, in execute
    self.webBruteforce(self.username, self.wordlist, self.service, self.delay)
  File "faitagram", line 272, in webBruteforce
    self.stopTOR()
  File "faitagram", line 81, in stopTOR
    tor_process.kill()
NameError: global name 'tor_process' is not defined

What do you think I should do?
I would like to assist in this in any way possible

**Comment by Juniorn1003** [comment]
There you go. Problem solved, Just changed the tor_process.kill to service tor stop.

**Comment by PlaguedByWeirdness** [comment]
Dammit, almost worked 

Now I get:

Traceback (most recent call last):
  File "faitagram", line 277, in <module>
    main()
  File "faitagram", line 44, in main
    if os.path.exists(wordlist) == False:
  File "/usr/lib/python2.7/genericpath.py", line 26, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
