### ISSUE TITLE
Got connection refused

### ISSUE THREAD

**Issue by maumau35** [Juniorn1003/Faitagram#29]
after doing this
python faitagram -s instagram -u username -w wlist

[ ok ] Restarting tor (via systemctl): tor.service.
[ ok ] Successfully Scanned Password : 872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C
Traceback (most recent call last):
  File "faitagram", line 299, in <module>
    main()
  File "faitagram", line 79, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 131, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 148, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by Juniorn1003** [comment]
In your geckodriver.log, it should say : "Error: GDK_BACKEND does not match available displays"
Which means that you did not have pyvirtualdisplay and xvfb installed. 
Why does almost everyone doesn't run the setup.py

**Comment by maumau35** [comment]
No, I get network error not fetched currently on mobile
