### ISSUE TITLE
help

### ISSUE THREAD

**Issue by splendid31** [Juniorn1003/Faitagram#3]
Traceback (most recent call last):
  File "faitagram", line 159, in <module>
    main()
  File "faitagram", line 47, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 66, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 77, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by Juniorn1003** [comment]
You have to install selenium.

**Comment by splendid31** [comment]
i followed ur message but its give me this :  
root@kali:~# pip install -U selenium
Requirement already up-to-date: selenium in /usr/local/lib/python2.7/dist-packages

**Comment by splendid31** [comment]
i followed ur message but its give me this :  
root@kali:~# pip install -U selenium
Requirement already up-to-date: selenium in /usr/local/lib/python2.7/dist-packages

**Comment by splendid31** [comment]
i sloved my problem thx......i pudate to fitrefox quantum 57
