### ISSUE TITLE
I have no clue what is going on

### ISSUE THREAD

**Issue by blazegamingHD1** [Juniorn1003/Faitagram#31]
I used the install file and turned on the service for tor, but I get this message when trying to use it and I have no idea what is going on.
Here is the terminal log:

[ ok ] Restarting tor (via systemctl): tor.service.
[ ok ] Successfully Scanned Password : 872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C
Traceback (most recent call last):
  File "faitagram", line 306, in <module>
    main()
  File "faitagram", line 81, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 136, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 153, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 148, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

Please help

**Comment by Juniorn1003** [comment]
Try again. I updated the script, it will work now. By the way, I hope you are not using a other OS.
