### ISSUE TITLE
Still getting Webdriver connection refused

### ISSUE THREAD

**Issue by SpartanKing4** [Juniorn1003/Faitagram#33]
I have updated Faitagram to the last version but i still get the same selenium.WebdriverException connection refused error :

[ ok ] Restarting tor (via systemctl): tor.service.
[ ok ] Successfully Scanned Password : 872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C
Traceback (most recent call last):
  File "faitagram", line 306, in <module>
    main()
  File "faitagram", line 79, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 138, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 157, in usercheck
    driver = webdriver.Firefox(executable_path="/usr/local/bin/geckodriver")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

I have executed the setup and all of that .

**Comment by Juniorn1003** [comment]
Then what version is your firefox? It should be above 57.0.2 and check what it says in your geckodriver.log.

**Comment by Juniorn1003** [comment]
To fix it, you can also just do this:

Git stash
Git pull
Git stash pop

**Comment by Juniorn1003** [comment]
Apparently no. It is a error in selenium, probably geckodriver issue. I won't close this issue until geckodriver and selenium fix this issue. But if you want it to make it work right now, then downgrade to v45 in firefox.

**Comment by SpartanKing4** [comment]
Alright bruh , gonna try downgrading

**Comment by Juniorn1003** [comment]
This error is fixed now. Try again, And sorry for keep making download again.
