### ISSUE TITLE
Still getting problems

### ISSUE THREAD

**Issue by blazegamingHD1** [Juniorn1003/Faitagram#34]
I downloaded your latest update and when typing in the command, it said about restarting tor service and then it didn't do anything and then finally it ended up coming up with a error. btw im using kali linux like you need.
Here is the terminal log:

[ ok ] Restarting tor (via systemctl): tor.service.
[ ok ] Successfully Scanned Password : 872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C

Traceback (most recent call last):
  File "faitagram", line 306, in <module>
    main()
  File "faitagram", line 79, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 138, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 157, in usercheck
    driver = webdriver.Firefox(executable_path="/usr/local/bin/geckodriver")
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

**Comment by maumau35** [comment]
Update
Cd Faitagram
Git stash
Git pull
Git stash pop
Should fix it, but after that you will encounter another bug where @juniorn3000 is working on

**Comment by Juniorn1003** [comment]
duplicate as #33 ..... Go there.
