### ISSUE TITLE
Unable to find matching set of capabilities

### ISSUE THREAD

**Issue by yammowram** [Juniorn1003/Faitagram#40]
So I removed Firefox version 52 ESR, the version that came with Kali out of the box, and installed firefox 58 but I'm facing this issue right here:

```
[ ok ] Restarting tor (via systemctl): tor.service.
[ ok ] Successfully Scanned Password : 872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C
Traceback (most recent call last):
  File "faitagram", line 267, in <module>
    main()
  File "faitagram", line 75, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 101, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 118, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities

```

**Comment by Juniorn1003** [comment]
What version of firefox do you have?

**Comment by yammowram** [comment]
Ok, changed the line to download v19 in the setup.py. I thought I removed firefox 52ESR from Kali, but the script seems to open v52 up and not the new version that I downloaded. Is that due to a certain line of code in setup.py?

**Comment by MelissaMV** [comment]
That's the same issue I'm having @Juniorn1003 fix it before i whack you on the head hehe lol jk

**Comment by Juniorn1003** [comment]
@yammowram  Will fix this.

**Comment by yammowram** [comment]
Much thanks @Juniorn1003!

**Comment by Juniorn1003** [comment]
Try running the setup.py again, I did some changes. It will now read the firefox version of yours, then install the right geckodriver version.

**Comment by yammowram** [comment]
Thanks for the changes. The code gets my version, which is v58, and installs the correct geckodriver version. But Firefox52 ESR is still being installed and I figured out why. The command: `sudo apt-get install firefoxdriver` installs `firefox-esr phantomjs python-selenium`. I'm not sure if there's another command that will not install firefox-esr

**Comment by Juniorn1003** [comment]
@yammowram Ok, I just removed that line since all the latest Kali has Firefox pre-installed.

**Comment by Juniorn1003** [comment]
Well then, I think this issue is closed.

**Comment by yammowram** [comment]
Sorry about that @Juniorn1003, these have been a very busy couple days. I just pulled the latest changes and it no longer installs the old version of Firefox! Gecko v19 downloads and installs. When running `python faitagram ...` I get this:

`[ ok ] Restarting tor (via systemctl): tor.service.
[ ok ] Successfully Scanned Password : 872860B76453A77D60CA2BB8C1A7042072093276A3D701AD684053EC4C
Traceback (most recent call last):
  File "faitagram", line 267, in <module>
    main()
  File "faitagram", line 75, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 101, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 118, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: Unable to find a matching set of capabilities
`

Very confusing to me as everything is already in place. Firefox v58 has been installed in my /etc/ directory and gecko v19 is downloaded and installed as per the setup.py.

**Comment by zhongw117** [comment]
For me only installed a latest version firefox solved.
