### ISSUE TITLE
General SOCKS server error

### ISSUE THREAD

**Issue by scratchfive** [Juniorn1003/Faitagram#41]
After testing the third password, I receive the following error:

```
Error : 0x01: General SOCKS server failure
Traceback (most recent call last):
  File "faitagram", line 267, in <module>
    main()
  File "faitagram", line 75, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 109, in execute
    self.webBruteforce(self.username, self.wordlist, self.service, self.delay)
  File "faitagram", line 258, in webBruteforce
    driver.close()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 679, in close
    self.execute(Command.CLOSE)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 489, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1076, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/lib/python2.7/httplib.py", line 924, in putrequest
    raise CannotSendRequest()
httplib.CannotSendRequest
```

**Comment by Juniorn1003** [comment]
This is the only error that I have to encounter. And, this is a duplicate as  #13
