### ISSUE TITLE
How do i fix this

### ISSUE THREAD

**Issue by SallHall** [Juniorn1003/Faitagram#43]
sh: 1: /etc/init.d/tor: not found
Traceback (most recent call last):
  File "faitagram", line 267, in <module>
    main()
  File "faitagram", line 65, in main
    with open('/etc/tor/torrc','r') as f:
IOError: [Errno 2] No such file or directory: '/etc/tor/torrc'

My tor browser working fine but error is still there

**Comment by antony-jr** [comment]
This error occurs because you don't have the tor server installed ( not tor browser ).
Can I know what service are you attacking ?

**Comment by SallHall** [comment]
how do i do that?
Just trying out and learning to operate Kali
I wanted to try out brute force on Instagram

**Comment by antony-jr** [comment]
@SallHall Please use this tool , The Video Tutorial is here -> https://www.youtube.com/watch?v=KZEcFn3Z5L0  

THIS IS ONLY FOR INSTAGRAM! 

Star the repo to support me , https://github.com/antony-jr/instagram-py 

**PLEASE SEE THAT A LOT OF COPIES OF INSTAGRAM-PY CLONES ARE OUT THERE BUT I'M THE ORIGINAL AUTHOR , MY FORMER USERNAME WAS DEATHSEC AND WAS STOLEN WHEN I DELETED MY USERNAME ON GITHUB** FOR MORE INFORMATION HEAD TO THE REPO OR TO GET STARTED HEAD TO THE YOUTUBE VIDEO

**REPO**: https://github.com/antony-jr/instagram-py 
**VIDEO TUTORIAL**: https://www.youtube.com/watch?v=KZEcFn3Z5L0
