### ISSUE TITLE
h

### ISSUE THREAD

**Issue by sleazerrrr** [Juniorn1003/Faitagram#50]
after everything install correctly and finally getting to the end i got this 

Error : Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused
Traceback (most recent call last):
  File "faitagram", line 254, in <module>
    main()
  File "faitagram", line 63, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 97, in execute
    self.webBruteforce(self.username, self.wordlist, self.service, self.delay)
  File "faitagram", line 245, in webBruteforce
    driver.quit()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 191, in quit
    RemoteWebDriver.quit(self)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 689, in quit
    self.execute(Command.QUIT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 489, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 566, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/dist-packages/socks.py", line 777, in connect
    raise ProxyConnectionError(msg, error)
socks.ProxyConnectionError: Error connecting to SOCKS5 proxy 127.0.0.1:9050: [Errno 111] Connection refused

**Comment by Juniorn1003** [comment]
Exactly in which step did this error occur?

**Comment by sleazerrrr** [comment]
right after the delay

**Comment by sleazerrrr** [comment]
everything was fine until it got to there

**Comment by Juniorn1003** [comment]
Duplicate as hshebab’s issue.
