### ISSUE TITLE
Error : 0x01: General SOCKS server failure

### ISSUE THREAD

**Issue by xTF5x** [Juniorn1003/Faitagram#53]
I got same error (twitter,instagram)
Error : 0x01: General SOCKS server failure
Traceback (most recent call last):
  File "faitagram", line 254, in <module>
    main()
  File "faitagram", line 63, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 97, in execute
    self.webBruteforce(self.username, self.wordlist, self.service, self.delay)
  File "faitagram", line 245, in webBruteforce
    driver.quit()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 191, in quit
    RemoteWebDriver.quit(self)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 689, in quit
    self.execute(Command.QUIT)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 310, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 466, in execute
    return self._request(command_info[0], url, body=data)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/remote_connection.py", line 489, in _request
    self._conn.request(method, parsed_url.path, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1042, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1082, in _send_request
    self.endheaders(body)
  File "/usr/lib/python2.7/httplib.py", line 1038, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 882, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 844, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 821, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 566, in create_connection
    sock.connect(sa)
  File "/usr/lib/python2.7/dist-packages/socks.py", line 784, in connect
    negotiate(self, dest_addr, dest_port)
  File "/usr/lib/python2.7/dist-packages/socks.py", line 449, in _negotiate_SOCKS5
    CONNECT, dest_addr)
  File "/usr/lib/python2.7/dist-packages/socks.py", line 524, in _SOCKS5_request
    raise SOCKS5Error("{0:#04x}: {1}".format(status, error))
socks.SOCKS5Error: 0x01: General SOCKS server failure

**Comment by marcos10soares** [comment]
+1
I have the same error

**Comment by Nasaman1984** [comment]
yep same here

**Comment by Juniorn1003** [comment]
Duplicate as hshebab’s issue.

**Comment by PabloGamerYTB** [comment]
How ?

**Comment by Palmus84** [comment]
Hi is there any remedy? Anyone fixed it?
