### ISSUE TITLE
Weird problem

### ISSUE THREAD

**Issue by kifs** [Juniorn1003/Faitagram#59]
Hey, I just run the script with setup.py an then do python faitagram -s twitter -u USERNAME -w wlist.
And I've this message : 

sh: 1: /etc/init.d/tor: not found
Traceback (most recent call last):
  File "faitagram", line 254, in <module>
    main()
  File "faitagram", line 63, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 89, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 102, in usercheck
    display = Display(visible=0, size=(800, 600)) # Pyvirtual display starting
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/usr/local/lib/python2.7/dist-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/usr/local/lib/python2.7/dist-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error!

Thank you

**Comment by Juniorn1003** [comment]
Try downloading the script again and run it again. I am sure this is a bug or a Xvfb problem.

**Comment by kifs** [comment]
Hey, I downloaded the script 3 times, I 

> did sudo apt - get install xvfb 

and its still doesn't work :(
