### ISSUE TITLE
OSError: [Errno 8] Exec format error

### ISSUE THREAD

**Issue by ColeShelly** [Juniorn1003/Faitagram#61]
[ ok ] Restarting tor (via systemctl): tor.service.
Traceback (most recent call last):
  File "faitagram", line 254, in <module>
    main()
  File "faitagram", line 63, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 89, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 106, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error

??? Please Help!

**Comment by dabslabcab** [comment]
same happened with me. Haven't found a fix so far.
