### ISSUE TITLE
How to run on mac OS

### ISSUE THREAD

**Issue by lijijordan** [Juniorn1003/Faitagram#7]
`Checking Username...

Traceback (most recent call last):
  File "faitagram", line 159, in <module>
    main()
  File "faitagram", line 47, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 66, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 75, in usercheck
    display = Display(visible=0, size=(800, 600))
  File "/Library/Python/2.7/site-packages/pyvirtualdisplay/display.py", line 34, in __init__
    self._obj = self.display_class(
  File "/Library/Python/2.7/site-packages/pyvirtualdisplay/display.py", line 52, in display_class
    cls.check_installed()
  File "/Library/Python/2.7/site-packages/pyvirtualdisplay/xvfb.py", line 38, in check_installed
    ubuntu_package=PACKAGE).check_installed()
  File "/Library/Python/2.7/site-packages/easyprocess/__init__.py", line 180, in check_installed
    raise EasyProcessCheckInstalledError(self)
easyprocess.EasyProcessCheckInstalledError: cmd=['Xvfb', '-help']
OSError=[Errno 2] No such file or directory
Program install error!`

**Comment by Juniorn1003** [comment]
This script was for Linux, not Mac. If you still want to use it, then you would have to install the requirements using the tar files.
