### ISSUE TITLE
what is wrong with webdriver ?

### ISSUE THREAD

**Issue by lijijordan** [Juniorn1003/Faitagram#8]
Please  help me.

root@ubuntu-512mb-0905-snapshots-bootscript-kcptun-512mb-nyc3-09:~/Faitagram# sudo python faitagram -s facebook -u MeMeBigBoy@gmail.com -w ./wlist -d 10
Checking Username...

Traceback (most recent call last):
  File "faitagram", line 159, in <module>
    main()
  File "faitagram", line 47, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 66, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 77, in usercheck
    driver = webdriver.Firefox()
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 51, in __init__
    self.binary, timeout),
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/extension_connection.py", line 47, in __init__
    self.binary.launch_browser(self.profile)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 43, in launch_browser
    self._start_from_profile_path(self.profile.path)
  File "/usr/lib/python2.7/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 65, in _start_from_profile_path
    env=self._firefox_env).communicate()
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
AttributeError: 'NoneType' object has no attribute 'rfind'
root@ubuntu-512mb-0905-snapshots-bootscript-kcptun-512mb-nyc3-09:~/Faitagram#

**Comment by Juniorn1003** [comment]
Do you have selenium installed?
