### ISSUE TITLE
Selenium Webdriver connection refused

### ISSUE THREAD

**Issue by flyingraccoon** [Juniorn1003/Faitagram#9]
Output:
Traceback (most recent call last):
  File "faitagram", line 159, in <module>
    main()
  File "faitagram", line 47, in main
    Bruter(service, username, wordlist, delay).execute()
  File "faitagram", line 66, in execute
    if self.usercheck(self.username, self.service) == 1:
  File "faitagram", line 77, in usercheck
    driver = webdriver.Firefox()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/firefox/webdriver.py", line 158, in __init__
    keep_alive=True)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 311, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: connection refused

Geckodriver runs fine though and i tried pip install -U selenium and it still didn't work

**Comment by AlzMa** [comment]
Found a solution to your problem flyingraccoon. 
Either you read this article: [Press this](https://stackoverflow.com/questions/40208051/selenium-using-python-geckodriver-executable-needs-to-be-in-path)

Or you just put this into terminal: (line by line)
```
wget https://github.com/mozilla/geckodriver/releases/download/v0.9.0/geckodriver-v0.9.0-linux64.tar.gz
tar -xvzf geckodriver-v0.9.0-linux64.tar.gz
rm geckodriver-v0.9.0-linux64.tar.gz
chmod +x geckodriver
cp geckodriver wires
export PATH=$PATH:/root/bin/wires
export PATH=$PATH:/root/bin/geckodriver

ipython
%cpaste


browser = None
def StartSelenium():
import selenium
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import binascii
import hashlib
firefox_capabilities = DesiredCapabilities.FIREFOX
firefox_capabilities['marionette'] = True
firefox_capabilities['binary'] = '/usr/bin/firefox'
global browser
browser = webdriver.Firefox(capabilities=firefox_capabilities)
browser.get('https://www.google.com')
```

I found the code on a youtubevideo 👍

**Comment by Juniorn1003** [comment]
Thanks, AlzMa!

**Comment by AlzMa** [comment]
My pleasure, @juniorn1003!
